import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :pou_con, PouConWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Force SSL redirect (compile-time option)
  # This redirects HTTP to HTTPS automatically
  force_ssl: [rewrite_on: [:x_forwarded_proto], host: nil]

# Do not print debug messages in production
config :logger, level: :info

# Use local Tailwind binary to avoid download issues during Docker builds
# Download from: https://github.com/tailwindlabs/tailwindcss/releases/download/v4.1.7/tailwindcss-linux-arm64
# Save to: assets/vendor/bin/tailwindcss-linux-arm64
config :tailwind, path: Path.expand("../assets/vendor/bin/tailwindcss-linux-arm64", __DIR__)

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
