import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :pou_con, PouConWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Force SSL redirect (compile-time option)
  # This redirects HTTP to HTTPS automatically
  force_ssl: [rewrite_on: [:x_forwarded_proto], host: nil]

# Do not print debug messages in production
config :logger, level: :info

workspace_prod_arm64 = Path.expand("../../shared_config/prod_arm64.exs", __DIR__)

if File.exists?(workspace_prod_arm64) do
  import_config workspace_prod_arm64
end

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
